plugins:
  - jekyll-seo-tag

header_pages:
  - about.md
  - projects.html
  - blogs.html
  - guides.html

collections:
  guides:
    output: true
  posts:
    output: true
  videos:
    output: true

style: dark
listen_for_clients_preferred_style: true
