markdown: kramdown

plugins:
  - jekyll-seo-tag

header_pages:
  - about.md
  - projects.html
  - guides.html

collections:
  guides:
    output: true
  posts:
    output: true

hosted_at: https://github.com/walcht/walcht/blob/master/

style: dark
listen_for_clients_preferred_style: true
